apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: logging
  labels:
    k8s-app: filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      serviceAccountName: filebeat
      containers:
        - name: filebeat
          image: docker.elastic.co/beats/filebeat:8.13.2
          args: ["-c", "/etc/filebeat.yml", "-e"]
          resources:
            limits:
              memory: 200Mi
              cpu: 100m
          volumeMounts:
            - name: config
              mountPath: /etc/filebeat.yml
              subPath: filebeat.yml

            # Container stdout logs
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlogcontainers
              mountPath: /var/log/containers
              readOnly: true
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibkubelet
              mountPath: /var/lib/kubelet
              readOnly: true

            # Spring Boot file logs
            - name: applogs
              mountPath: /var/log/app
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: filebeat-config

        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
        - name: varlogcontainers
          hostPath:
            path: /var/log/containers
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibkubelet
          hostPath:
            path: /var/lib/kubelet

        # Volume untuk Spring Boot log
        - name: applogs
          hostPath:
            path: /var/log/app
