apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
data:
  filebeat.yml: |
    filebeat.inputs:
      
      - type: container
        enabled: true
        paths:
          - /var/log/containers/*.log
        multiline.pattern: '^[[:space:]]'
        multiline.negate: false
        multiline.match: after

     
      - type: log
        enabled: true
        paths:
          - /var/log/app/*.log
        multiline.pattern: '^[[:space:]]'
        multiline.negate: false
        multiline.match: after

    processors:
      - add_cloud_metadata: ~
      - add_host_metadata: ~

    output.logstash:
      hosts: ["logstash.logging.svc.cluster.local:5044"]
