FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN apt-get update && \
    apt-get install -y docker.io unzip curl gnupg software-properties-common && \
    curl -L https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz -o oc.tar.gz && \
    tar -xzvf oc.tar.gz -C /usr/local/bin oc kubectl && \
    rm oc.tar.gz

# Allow Jenkins user to use Docker
RUN usermod -aG docker jenkins

USER jenkins