version: "3.8"
services:
  jenkins:
    build:
      context: . #Artinya direktori tempat Docker akan membangun image adalah direktori saat ini
      dockerfile: Dockerfile.jenkins #Menentukan nama file Dockerfile yang digunakan untuk membangun image Jenkins-nya, yaitu Dockerfile.jenkins
    image: jenkins-custom:latest #Memberi nama hasil build-nya menjadi image bernama jenkins-custom dengan tag latest.
    container_name: jenkins
    user: "0:0" 
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock   # <--- Ini penting agar Jenkins bisa akses Docker Engine host
    privileged: true
    networks:
      - cicd-net

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --url http://jenkins:8080
    networks:
      - cicd-net
    depends_on:
      - jenkins

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9001:9000"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - cicd-net

  cloudflared-sonar:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-sonar
    command: tunnel --url http://sonarqube:9000
    networks:
      - cicd-net
    depends_on:
      - sonarqube
  db:
    image: postgres:13
    container_name: sonar-postgres
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - cicd-net

volumes:
  jenkins_home:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  postgresql:
  postgresql_data:

networks:
  cicd-net:
    driver: bridge