# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: backend
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: backend
#   template:
#     metadata:
#       labels:
#         app: backend
#     spec:
#       containers:
#         - name: backend
#           image: asia-southeast2-docker.pkg.dev/am-finalproject/backend-repo/api:latest
#           ports:
#             - containerPort: 8080
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend
# spec:
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default # Asumsi namespace default, sesuaikan jika berbeda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        # Container Aplikasi Backend Anda
        - name: backend
          image: asia-southeast2-docker.pkg.dev/am-finalproject/backend-repo/api:latest
          ports:
            - containerPort: 8080
          # START: Tambahkan konfigurasi volume log di sini
          volumeMounts:
            - name: app-log-volume
              mountPath: /var/log/app
          # END: Tambahkan konfigurasi volume log di sini
      # START: Tambahkan konfigurasi volume di sini
      volumes:
        - name: app-log-volume
          hostPath:
            path: /var/log/app
            type: DirectoryOrCreate
      # END: Tambahkan konfigurasi volume di sini
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: default # Asumsi namespace default, sesuaikan jika berbeda
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer