apiVersion: v1
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      id: my-app-logs
      enabled: true
      paths:
        - /var/log/app/*.log
    output.logstash:
      hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]
    logging.level: info
    logging.to_files: false
    logging.to_stderr: true
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"filebeat.yml":"filebeat.inputs:\n- type: log\n  id: my-app-logs\n  enabled: true\n  paths:\n    - /var/log/app/*.log\noutput.logstash:\n  hosts: [\"${LOGSTASH_HOST}:${LOGSTASH_PORT}\"]\nlogging.level: info\nlogging.to_files: false\nlogging.to_stderr: true\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"filebeat-config","namespace":"logging"}}
  creationTimestamp: "2025-08-03T03:35:01Z"
  name: filebeat-config
  namespace: logging
  resourceVersion: "1754192101917247014"
  uid: 80f69d74-6e78-4fc6-a6ef-d6e56d0ce716
