apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: asia-southeast2-docker.pkg.dev/am-finalproject/fathya-backend-repo/be-app:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - name: firebase-secret
              mountPath: /app/firebase
              readOnly: true
      volumes:
        - name: firebase-secret
          secret:
            secretName: firebase-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-app
spec:
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend-app
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`backend.42n.fun`)
      kind: Rule
      services:
        - name: backend-service
          port: 8080