    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: elasticsearch-config
      namespace: logging
    data:
      elasticsearch.yml: |
        cluster.name: elasticsearch-cluster
        node.name: ${HOSTNAME}
        network.host: 0.0.0.0
        http.port: 9200
        discovery.type: single-node
        xpack.security.enabled: false
        
    