apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: logging
  labels:
    io.kompose.service: elasticsearch-data
  name: elasticsearch-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard 