apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: logging
  labels:
    k8s-app: filebeat # Perbarui label menjadi k8s-app=filebeat
spec:
  selector:
    matchLabels:
      k8s-app: filebeat # Perbarui label menjadi k8s-app=filebeat
  template:
    metadata:
      labels:
        k8s-app: filebeat # Perbarui label menjadi k8s-app=filebeat
    spec:
      serviceAccountName: filebeat # Disarankan untuk keamanan
      terminationGracePeriodSeconds: 30 # Disarankan untuk shutdown yang graceful
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.4.0
        args:
          - "-c"
          - /etc/filebeat.yml
          - "-e"
        env:
        # Menambahkan variabel lingkungan NODE_NAME untuk autodiscovery
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        # Menambahkan variabel lingkungan untuk Logstash, jika diperlukan oleh filebeat.yml
        # Jika filebeat.yml sudah memiliki hosts, baris ini bisa dihilangkan
        - name: LOGSTASH_HOST
          value: "logstash.logging.svc.cluster.local"
        - name: LOGSTASH_PORT
          value: "5044"
        securityContext:
          runAsUser: 0 # Menjalankan sebagai root untuk membaca log
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          subPath: filebeat.yml
        # Menambahkan volume mount yang diperlukan untuk autodiscovery container
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers