apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: filestream
      id: my-app-logs
      enabled: true
      paths:
        - /var/log/app/*.log
    output.logstash:
      hosts: ["${LOGSTASH_HOST}:${LOGSTASH_PORT}"]
    logging.level: info
    logging.to_files: false
    logging.to_stderr: true
