apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-cm0-configmap
  namespace: logging
  labels:
    io.kompose.service: logstash
data:
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }

    filter {
      # 1) Grok utama untuk memecah baris log Spring Boot
      grok {
        match => {
          "message" => [
            "%{YEAR:timestamp_year}-%{MONTHNUM:timestamp_month}-%{MONTHDAY:timestamp_day} %{TIME:timestamp_time}(?:Z)? %{LOGLEVEL:level}%{SPACE}+%{INT:pid}%{SPACE}+---%{SPACE}+\\[%{DATA:thread_name}\\]%{SPACE}+%{JAVACLASS:logger}%{SPACE}+:%{SPACE}+%{GREEDYDATA:log_message_full}",
            "%{YEAR:timestamp_year}-%{MONTHNUM:timestamp_month}-%{MONTHDAY:timestamp_day} %{TIME:timestamp_time} %{LOGLEVEL:level}%{SPACE}+%{JAVACLASS:logger}%{SPACE}+%{DATA:kv_data_raw}%{SPACE}+-%{SPACE}+%{GREEDYDATA:log_message_full}"
          ]
        }
        tag_on_failure => ["_grokparsefailure_main_log"]
      }

      # 2) Ekstrak key=value dari 'kv_data_raw' jika ada
      if [kv_data_raw] {
        kv {
          source         => "kv_data_raw"
          field_split    => " "
          value_split    => "="
          include_keys   => ["eventType", "user"]
          remove_field   => ["kv_data_raw"]
          tag_on_failure => ["_kvparsefailure"]
        }
      }

      # 3) Grok untuk mengekstrak detail dari 'log_message_full'
      grok {
        match => {
          "log_message_full" => [
            "Completed %{NUMBER:http.response.status_code:int} %{WORD:http.response.status_message}",
            "%{WORD:http.request.method} \"%{URIPATH:url.path}\"(?:, parameters=%{DATA:http.request.parameters})?",
            "Mapped to %{JAVACLASS:mapped_class_method}",
            "Read \"%{DATA:content_type}\" to \\[%{DATA:request_body_info}\\]",
            "Writing \\[\\[%{DATA:response_kv_string}\\]\\]",
            "Writing \\[%{DATA:response_kv_string}\\]",
            "Resolved \\[org\\.springframework\\.web\\.bind\\.MethodArgumentNotSupportedException: %{GREEDYDATA:validation_error_details}\\]",
            "Resolved \\[org\\.springframework\\.web\\.server\\.ResponseStatusException: %{NUMBER:resolved_status_code:int} %{WORD:resolved_status_message} \"%{GREEDYDATA:resolved_error_message}\"\\]",
            "%{GREEDYDATA:plain_log_message}"
          ]
        }
        remove_field   => ["log_message_full"]
        tag_on_failure => ["_grokparsefailure_details"]
      }

      # 4) KV untuk parsing 'response_kv_string' (jika ada)
      if [response_kv_string] {
        kv {
          source         => "response_kv_string"
          field_split    => ", "
          value_split    => "="
          target         => "response_data"
          remove_field   => ["response_kv_string"]
          tag_on_failure => ["_kvparsefailure_response_data"]
        }
      }

      # 5) Mutate: mapping field ke ECS (jika perlu)
      mutate {
        rename => {
          "http_method"         => "[http][request][method]"
          "http_request_path"   => "[url][path]"
          "http_request_params" => "[url][query]"
        }
      }

      # 6) Hapus eventType jika nilainya "user="
      if [eventType] == "user=" {
        mutate {
          remove_field => ["eventType"]
        }
      }

      # 7) Drop log "Login attempt"
      if [plain_log_message] == "Login attempt" {
        drop {}
      }

      8) Penentuan message & target_index khusus
      # if [eventType] == "blocked_user" {
      #   mutate {
      #     replace => { "message" => "User %{user} account is blocked: %{plain_log_message}" }
      #     replace => { "[@metadata][target_index]" => "app-blocked-user-%{+YYYY.MM.dd}" }
      #   }
      # } else 
      if [eventType] == "login_failed" {
        mutate {
          replace => { "message" => "User %{user} login failed: %{plain_log_message}" }
          replace => { "[@metadata][target_index]" => "app-login-failed-%{+YYYY.MM.dd}" }
        }
      } else if [eventType] == "login" {
        if [user] {
          mutate {
            replace => { "message" => "User %{user} logged in." }
            replace => { "[@metadata][target_index]" => "app-login-%{+YYYY.MM.dd}" }
          }
        } else {
          mutate {
            replace => { "message" => "Login event occurred." }
            replace => { "[@metadata][target_index]" => "app-login-%{+YYYY.MM.dd}" }
          }
        }
      } else {
        mutate {
          replace => { "message" => "%{[event][original]}" }
          replace => { "[@metadata][target_index]" => "app-others-%{+YYYY.MM.dd}" }
        }
      }

      # 9) Date parsing
      date {
        match         => ["%{timestamp_year}-%{timestamp_month}-%{timestamp_day} %{TIME:timestamp_time}", "yyyy-MM-dd HH:mm:ss"]
        target        => "@timestamp"
        remove_field  => ["timestamp_year", "timestamp_month", "timestamp_day", "timestamp_time"]
      }
    }

    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "%{[@metadata][target_index]}"
      }
      stdout { codec => rubydebug }
    }
