apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: logging
  labels:
    io.kompose.service: logstash
data:
  logstash.conf: |
    input {
      file {
        path            => "/usr/share/logstash/logs/application.log*"
        start_position  => "beginning"
        sincedb_path    => "/usr/share/logstash/logs/.sincedb"
        codec           => plain { charset => "UTF-8" }
      }
    }

    filter {
      # 1) Ekstrak pasangan key=value dari setiap baris
      kv {
        field_split   => " "
        value_split   => "="
        include_keys  => ["eventType", "user"]
      }

      # 2) Jika log-nya berupa JSON, parse menjadi field
      if [message] =~ /^\{.*\}$/ {
        json {
          source       => "message"
          remove_field => ["message"]
        }
      }

      # 3) Tentukan target index berdasarkan eventType
      if [eventType] == "registration" {
        mutate {
          add_field => { "[@metadata][target_index]" => "app-registration-%{+YYYY.MM.dd}" }
        }
      } else if [eventType] == "login" {
        mutate {
          add_field => { "[@metadata][target_index]" => "app-login-%{+YYYY.MM.dd}" }
        }
      } else {
        mutate {
          add_field => { "[@metadata][target_index]" => "app-others-%{+YYYY.MM.dd}" }
        }
      }
    }

    output {
      elasticsearch {
        hosts    => ["http://elasticsearch:9200"]
        user     => "elastic"            # Ganti sesuai username Elasticsearch
        password => "MyS3cr3tPass"       # Ganti dengan password yang benar
        index    => "%{[@metadata][target_index]}"
      }

      stdout {
        codec => rubydebug              # Debug ke output console Logstash
      }
    }
