
# Middleware untuk rate limit siang hari (05:00-19:00)
# Limit: 100 req/min dengan burst 150
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit-day
  namespace: default
spec:
  rateLimit:
    burst: 100
    average: 50
    period: 1m
    sourceCriterion:
      ipStrategy:
        depth: 1

---
# Middleware untuk rate limit malam hari (19:00-05:00)
# Limit: 50 req/min dengan burst 75
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: rate-limit-night
  namespace: default
spec:
  rateLimit:
    burst: 60
    average: 30
    period: 1m
    sourceCriterion:
      ipStrategy:
        depth: 1