apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-app-monitor
  namespace: monitoring  # ← Ubah ke namespace monitoring
  labels:
    release: prometheus 
spec:
  selector:
    matchLabels:
      app: backend-app e
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: 15s
  namespaceSelector:
    matchNames:
    - default  # ← Ini tetap default karena backend ada di namespace default